language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
script:
 - dotnet build -f netstandard2.0
 - dotnet build -f netstandard2.1
 - dotnet build -f netcoreapp2.0
 - dotnet build -f netcoreapp2.1
 - dotnet build -f netcoreapp2.2
 - dotnet build -f netcoreapp3.0
 - dotnet build -f netcoreapp3.1
